sudo: false
language: python
cache:
  - pip
python:
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install -U wheel
  - pip install tox-travis
script: tox
addons:
  apt_packages:
    - pandoc
